name    'alkivi-dhcpd'
version '0.0.1'
source 'https://github.com/alkivi-sas/puppet-dhcpd'
author 'alkivi'
license 'LGPLv3'
summary 'Controls DHCP server'
description 'Setup DHCP, handle client configuration in puppet'
project_page 'https://github.com/alkivi-sas/puppet-dhcpd'
dependency 'puppetlabs/stdlib', '>3.x'
dependency 'puppetlabs/concat', '1.0.0'
